<?php
//origin of request
// var_dump($_SERVER["HTTP_ORIGIN"]);


if ($_SERVER['REQUEST_METHOD'] == "GET") {
	echo "sike 😂😂";
	die();
}

require_once(__DIR__ . "/../class/db_class.php");
require_once(__DIR__ . "/../messenger/controllers/mailer_controller.php");

function generate_id()
{
	return md5(random_bytes((65)));
}

$action = $_POST["action"];

switch ($action) {
	case "contact_curator":
		$email = $_POST["email"];
		$db = new db_class();
		$prompt = $db->get_current_prompt($email);

		if(!$prompt){
			echo "You don't have any requests yet. We want to see what you will create";
			die();
		}
		//get prompt from request_id
		$prompt_text = $prompt["prompt_text"];
		$first = $prompt["user_name"];
		$number =$prompt["phone"];

		//get contact number
		//notify easyGo reps about the tour
		$message = "$first:$number<$email> has requested us to take a look at their itinery \n\n\n$prompt_text";
		$curl = curl_init();

			curl_setopt_array($curl, array(
			CURLOPT_URL => "https://hooks.slack.com/services/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",
			CURLOPT_RETURNTRANSFER => true,
			CURLOPT_ENCODING => '',
			CURLOPT_MAXREDIRS => 10,
			CURLOPT_TIMEOUT => 0,
			CURLOPT_FOLLOWLOCATION => true,
			CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
			CURLOPT_CUSTOMREQUEST => 'POST',
			CURLOPT_POSTFIELDS =>"{
				'text' : \"$message\"
			}",
			CURLOPT_HTTPHEADER => array(
				'Content-Type: application/json'
			),
			));

			$response = curl_exec($curl);

			curl_close($curl);
		echo "We have shared your request and a rep from easyGo will contact you in a few days";
		die();
	case "check_email":
		$email = $_POST["email"];
		$db = new db_class();
		$exists = $db->credentials_exist($email);

		if($exists){
			//generate token
			$token = generate_id();
			$db->store_token($email, $token);
			send_token($email, $token);
			echo 1;
			// echo "exists";
		}else {
			echo 0;
		}
		die();

		//send email;

	case "login":
		$name = $_POST["name"];
		$email = $_POST["email"];
		$number = $_POST["number"];

		$db = new db_class();
		$db->create_account($name, $email, "", $number);
		//generate token

		$token = generate_id();
		$db->store_token($email, $token);


		//send email;
		// echo $token;
		send_token($email, $token);
		echo "We have sent your login url to your email. Kindly wait a few seconds";
		die();
	case "generate":
		$activities = $_POST["activities"];
		$location = $_POST["locations"];
		$email = $_POST["email"];
		$db = new db_class();
		// echo json_encode(array(
		// 	"data" => explode(",",$activities))
		// );

		//create a request
		$request_id = $db->add_request($email);
		//save activities
		foreach(explode(",",$activities) as $current){
			$db->add_activity($current,$request_id);
		}
		//save loctions
		foreach(explode(",",$location) as $current){
			$db->add_location($current,$request_id);
		}


		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, 'https://api.openai.com/v1/chat/completions');
		curl_setopt($ch, CURLOPT_POST, true);
		curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode(array(
			'model' => 'gpt-3.5-turbo',
			'messages' => array(array(
				'role' => 'user',
				'content' => "Write a one day tour itinery as a Ghanaian company
				that was given this information: \n activities = $activities, locations = $location. Include
				prices where possible, two locations minimum and five activities minimum. Begin with the preface
				'This tour was generated by the coplanner AI system on easygo.com.gh. easyGo is a tour booking
				platform that provides unique experiences'."
			)
		),
			'temperature' => 0.7
		)));
		curl_setopt($ch, CURLOPT_HTTPHEADER, array(
			'Content-Type: application/json',
			'Authorization: Bearer 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'
		));
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

		$response = curl_exec($ch);

		if (curl_errno($ch)) {
			echo 'Error: ' . curl_error($ch);
		} else {
			//save response
			echo $response;
			$prompt_text = json_decode($response,true)["choices"][0]["message"]["content"];
			$db->save_response($request_id,$prompt_text);
		}

		curl_close($ch);
		die();
	default:
		echo "sike 😂😂";
		die();
}
