<?php
//origin of request
// var_dump($_SERVER["HTTP_ORIGIN"]);

if ($_SERVER['REQUEST_METHOD'] == "GET") {
	echo "sike 😂😂";
	die();
}

require_once(__DIR__ . "/../class/db_class.php");
require_once(__DIR__ . "/../messenger/controllers/mailer_controller.php");

function generate_id()
{
	return md5(random_bytes((65)));
}

$action = $_POST["action"];

switch ($action) {
	case "login":
		$name = $_POST["name"];
		$email = $_POST["email"];
		$institution = $_POST["institution"];
		$number = $_POST["number"];

		$db = new db_class();
		$db->create_account($name, $email, $institution, $number);
		//generate token
		$token = generate_id();
		$db->store_token($email, $token);


		//send email;
		echo $token;
		send_token($email, $token);
		die();
	case "generate":
		$activities = $_POST["activities"];
		$location = $_POST["locations"];
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, 'https://api.openai.com/v1/chat/completions');
		curl_setopt($ch, CURLOPT_POST, true);
		curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode(array(
			'model' => 'gpt-3.5-turbo',
			'messages' => array(array(
				'role' => 'user',
				'content' => "Write a one day tour itinery as a Ghanaian company
				that was given this information: \n activities = $activities, locations = $location. Include
				prices where possible, two locations minimum and five activities minimum. Begin with the preface
				'This tour was generated by the coplanner AI system on easygo.com.gh. easyGo is a tour booking
				platform that provides unique experiences'."
			)
		),
			'temperature' => 0.7
		)));
		curl_setopt($ch, CURLOPT_HTTPHEADER, array(
			'Content-Type: application/json',
			'Authorization: Bearer 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'
		));
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

		$response = curl_exec($ch);

		if (curl_errno($ch)) {
			echo 'Error: ' . curl_error($ch);
		} else {
			// var_dump($response);
			echo $response;
		}

		curl_close($ch);
		// var_dump($location);
		die();
	default:
		echo "sike 😂😂";
		die();
}
